/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ProjetG2_GUI.java
 *
 * Created on May 16, 2014, 10:46:40 AM
 */
/**
 *
 * @author david
 */

package projetg2;

import be.belgium.eid.eidlib.BeID;
import com.googlecode.javacv.FrameGrabber.Exception;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.dcm4che2.data.DicomObject;
import org.dcm4che2.data.Tag;


public class ProjetG2_GUI extends javax.swing.JFrame {
    private int index;
    public DicomManager MWL;
    List<DicomObject> MWLlist;
    /** Creates new form ProjetG2_GUI */
    
    public ProjetG2_GUI() {
        initComponents();
        MWL = new DicomManager();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField3 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButtonSTDMWL = new javax.swing.JButton();
        jButtonQueryMWL = new javax.swing.JButton();
        jButtonCreateCustomMWL = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButtonQueryMod = new javax.swing.JButton();
        jButtonPicture = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jButtonSTDMWL.setText("Create STD MWL");
        jButtonSTDMWL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonSTDMWLMouseClicked(evt);
            }
        });

        jButtonQueryMWL.setText("Print MWL");
        jButtonQueryMWL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonQueryMWLMouseClicked(evt);
            }
        });

        jButtonCreateCustomMWL.setText("Create Custom MWL");
        jButtonCreateCustomMWL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCreateCustomMWLMouseClicked(evt);
            }
        });

        jLabel1.setText("Create/print Custom MWL");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Modality");

        jButtonQueryMod.setText("Query MWL");
        jButtonQueryMod.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonQueryModMouseClicked(evt);
            }
        });

        jButtonPicture.setText("Take Picture");
        jButtonPicture.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPictureMouseClicked(evt);
            }
        });
        jButtonPicture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPictureActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Acquisition");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Body Part Examined");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jButtonCreateCustomMWL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonQueryMWL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonSTDMWL, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(32, 32, 32)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(15, 15, 15))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(jTextField2))
                                .addGap(83, 83, 83))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jButtonPicture, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(97, 97, 97)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addContainerGap()
                                        .addComponent(jButtonQueryMod, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonSTDMWL)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonQueryMWL, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCreateCustomMWL)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonQueryMod)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPicture)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButtonSTDMWLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSTDMWLMouseClicked
// TODO add your handling code here:
    //Bouton : Create MWL
    MWL.creeMWL();
}//GEN-LAST:event_jButtonSTDMWLMouseClicked

private void jButtonQueryMWLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQueryMWLMouseClicked
// TODO add your handling code here: 
    //Bouton Query MWL;
    MWLlist = MWL.queryMWL("","");
    int[] tagPathName = new int[] {Tag.PatientName};
    int[] tagPathMod = new int[] {Tag.Modality};
    MWLlist = MWL.queryMWL(jTextField1.getText(),jTextField2.getText());
    String toPrint= "";
    index = 0;
    jComboBox1.removeAllItems();
    
    //affiche la MWL dans le TextArea :
            for (int i = 0; i < MWLlist.size(); i++) {
                toPrint = toPrint +MWLlist.get(i).toString()+"\n" + "\n";
                jComboBox1.addItem(MWLlist.get(i).getString(tagPathName));
            }
    jTextArea1.setText(toPrint);
    MWLlist = MWL.queryMWL("","");
           
    
}//GEN-LAST:event_jButtonQueryMWLMouseClicked

private void jButtonCreateCustomMWLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCreateCustomMWLMouseClicked
// TODO add your handling code here:
    //custom Dicom MWL with eID acquisition
    BeID eID = new BeID(true);
    String mod = jTextField1.getText();
    String part = jTextField2.getText();
    if (mod == null | mod == ""){
        mod = "CT";
    }
    MWL.createCustomMWL(eID,mod,part);
}//GEN-LAST:event_jButtonCreateCustomMWLMouseClicked

private void jButtonQueryModMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonQueryModMouseClicked
// TODO add your handling code here:
    //query MMWL custom Modality
    MWLlist = MWL.queryMWL(jTextField1.getText(),jTextField2.getText());
    
    int[] tagPathName = new int[] {Tag.PatientName};
    int[] tagPathMod = new int[] {Tag.Modality};

    String toPrint= "";
    index =0;
    jComboBox1.removeAllItems();
            //affiche la MWL dans le TextArea :
            for (int i = 0; i < MWLlist.size(); i++) {
                toPrint = toPrint+ Integer.toString(i)+ " " + MWLlist.get(i).getString(tagPathName) + "  " + MWLlist.get(i).getString(tagPathMod) +  "\n";
                jComboBox1.addItem(MWLlist.get(i).getString(tagPathName));
            }
            jTextArea1.setText(toPrint);
}//GEN-LAST:event_jButtonQueryModMouseClicked

private void jButtonPictureMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPictureMouseClicked
// TODO add your handling code here:
    //take picture button
    //MWLlist
    //int i = Integer.parseInt(jTextField3.getText());
    int i = jComboBox1.getSelectedIndex();
    jComboBox1.removeItemAt(i);
    DicomCreate fileDCM = new DicomCreate(MWLlist.get(i),index);
    index++;
        try {
            fileDCM.takePicture();
            //fileDCM.createDicomFile();
        } catch (Exception ex) {
            Logger.getLogger(ProjetG2_GUI.class.getName()).log(Level.SEVERE, null, ex);
        }
}//GEN-LAST:event_jButtonPictureMouseClicked

private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jTextField1ActionPerformed

private void jButtonPictureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPictureActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jButtonPictureActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCreateCustomMWL;
    private javax.swing.JButton jButtonPicture;
    private javax.swing.JButton jButtonQueryMWL;
    private javax.swing.JButton jButtonQueryMod;
    private javax.swing.JButton jButtonSTDMWL;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
